require:
  - rubocop-rspec
  - rubocop-performance
  - ./ext/rubocop.rb
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    # binstubs, and other utilities
    - bin/**/*
    - vendor/**/*
    - vendor/**/.*
    # package testing gems
    - package-testing/vendor/**/*
    - package-testing/vendor/**/.*
    - tmp/**/*

# Layout
Layout/LineLength:
  Description: People have wide screens, use them.
  Max: 200

# RSpec
RSpec/BeforeAfterAll:
  Description: Beware of using after(:all) as it may cause state to leak between tests. A necessary evil in acceptance testing.
  Exclude:
    - 'spec/acceptance/**/*.rb'
    - 'package-testing/spec/package/**/*.rb'

RSpec/NestedGroups:
  Description: Nested groups can lead to cleaner tests with less duplication
  Max: 10

RSpec/MessageSpies:
  EnforcedStyle: receive

Style/WordArray:
  EnforcedStyle: brackets

Style/SymbolArray:
  EnforcedStyle: brackets

Style/FormatStringToken:
  EnforcedStyle: template

# Metrics
Metrics/ParameterLists:
  Description: 6 is the current highest count. Lets not go over that.
  Max: 6

# PDK
PDK/FileFilePredicate:
  Exclude:
    - lib/pdk/util/filesystem.rb
    - Gemfile

PDK/FileExistPredicate:
  Exclude:
    - Rakefile
    - lib/pdk/util/filesystem.rb
    - package-testing/Rakefile

PDK/FileDirectoryPredicate:
  Exclude:
    - lib/pdk/util/filesystem.rb

PDK/FileUtilsMkdirP:
  Exclude:
    - lib/pdk/util/filesystem.rb
    - spec/acceptance/*
    - rakelib/command_spec.rake

PDK/FileExpandPath:
  Exclude:
    - lib/pdk/util/filesystem.rb
    - package-testing/**/*
    - rakelib/*
    - spec/spec_helper.rb
    - spec/acceptance/**/*.rb
    - pdk.gemspec

PDK/DirGlob:
  Exclude:
    - lib/pdk/util/filesystem.rb
    - rakelib/command_spec.rake

PDK/FileFnmatchPredicate:
  Exclude:
    - lib/pdk/util/filesystem.rb

PDK/FileReadablePredicate:
  Exclude:
    - lib/pdk/util/filesystem.rb
    - Gemfile

PDK/FileUtilsRm:
  Exclude:
    - lib/pdk/util/filesystem.rb
    - spec/acceptance/**/*.rb

PDK/FileRead:
  Exclude:
    - lib/pdk/util/filesystem.rb
    - spec/acceptance/**/*.rb
    - Gemfile
    - spec/unit/pdk/util/filesystem_spec.rb

PDK/FileZeroPredicate:
  Exclude:
    - lib/pdk/util/filesystem.rb

PDK/FileStat:
  Exclude:
    - lib/pdk/util/filesystem.rb

PDK/DirExistPredicate:
  Exclude:
    - rakelib/*.rake

PDK/DirBrackets:
  Exclude:
    - pdk.gemspec
    - spec/spec_helper_acceptance.rb
    - spec/spec_helper.rb
    - rakelib/*.rake
    - package-testing/spec/spec_helper_package.rb

PDK/FileOpen:
  Exclude:
    - lib/pdk/util/filesystem.rb
    - spec/unit/pdk/util/filesystem_spec.rb
    - Gemfile
    - spec/acceptance/**/*.rb
    - rakelib/*.rake
    - package-testing/Rakefile

PDK/FileSymlinkPredicate:
  Exclude:
    - lib/pdk/util/filesystem.rb

PDK/FileUtilsRMF:
  Exclude:
    - lib/pdk/util/filesystem.rb
    - spec/acceptance/**/*.rb

PDK/FileUtilsRMRF:
  Exclude:
    - lib/pdk/util/filesystem.rb
    - spec/acceptance/**/*.rb
    - rakelib/*.rake
    - spec/spec_helper_acceptance.rb

PDK/FileUtilsCP:
  Exclude:
    - lib/pdk/util/filesystem.rb
    - spec/acceptance/**/*.rb

PDK/FileUtilsMV:
  Exclude:
    - lib/pdk/util/filesystem.rb
    - spec/acceptance/**/*.rb

PDK/FileUtilsRemoveEntrySecure:
  Exclude:
    - lib/pdk/util/filesystem.rb
    - spec/acceptance/**/*.rb
